# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{furious-generators}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Trevor Oke"]
  s.date = %q{2009-12-10}
  s.description = %q{Custom generators for Rails applications}
  s.email = %q{trevor@trevoroke.com}
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/furious_generators.rb",
     "rails_generators/furious_auth/USAGE",
     "rails_generators/furious_auth/furious_auth_generator.rb",
     "rails_generators/furious_auth/templates/application_controller.rb",
     "rails_generators/furious_auth/templates/create_users.rb",
     "rails_generators/furious_auth/templates/user.rb",
     "rails_generators/furious_auth/templates/user_session.rb",
     "rails_generators/furious_auth/templates/user_sessions_controller.rb",
     "rails_generators/furious_auth/templates/users_controller.rb",
     "rails_generators/furious_auth/templates/views/user_sessions/new.rb",
     "rails_generators/furious_auth/templates/views/users/_form.erb",
     "rails_generators/furious_auth/templates/views/users/_form.rb",
     "rails_generators/furious_auth/templates/views/users/edit.html.erb",
     "rails_generators/furious_auth/templates/views/users/edit.rb",
     "rails_generators/furious_auth/templates/views/users/new.html.erb",
     "rails_generators/furious_auth/templates/views/users/new.rb",
     "rails_generators/furious_auth/templates/views/users/show.html.erb",
     "rails_generators/furious_auth/templates/views/users/show.rb",
     "rails_generators/furious_blueprint/USAGE",
     "rails_generators/furious_blueprint/furious_blueprint_generator.rb",
     "rails_generators/furious_blueprint/templates/ie.css",
     "rails_generators/furious_blueprint/templates/print.css",
     "rails_generators/furious_blueprint/templates/screen.css",
     "rails_generators/furious_jquery/USAGE",
     "rails_generators/furious_jquery/furious_jquery_generator.rb",
     "rails_generators/furious_jquery/templates/jquery-1.3.2.js",
     "rails_generators/furious_jquery/templates/jquery-ui-1.7.2.custom.min.js",
     "rails_generators/furious_layout/USAGE",
     "rails_generators/furious_layout/furious_layout_generator.rb",
     "rails_generators/furious_layout/templates/helper.rb",
     "rails_generators/furious_layout/templates/javascript.rb",
     "rails_generators/furious_layout/templates/layout-erb.rb",
     "rails_generators/furious_layout/templates/layout-haml.rb",
     "rails_generators/furious_layout/templates/stylesheet.rb"
  ]
  s.homepage = %q{http://github.com/thefury/furious-generators}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Custom generators for Rails applications}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

